// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceAPIKey = `-- name: CreateDeviceAPIKey :one

INSERT INTO device_api_keys (
  device_id,
  key_hash,
  key_prefix
) VALUES (
  $1::uuid,
  $2,
  $3
)
RETURNING id, device_id, key_hash, key_prefix, created_at, last_used_at, revoked_at
`

type CreateDeviceAPIKeyParams struct {
	DeviceID  pgtype.UUID `json:"device_id"`
	KeyHash   string      `json:"key_hash"`
	KeyPrefix string      `json:"key_prefix"`
}

// queries/device_api_keys.sql
func (q *Queries) CreateDeviceAPIKey(ctx context.Context, arg CreateDeviceAPIKeyParams) (DeviceApiKey, error) {
	row := q.db.QueryRow(ctx, createDeviceAPIKey, arg.DeviceID, arg.KeyHash, arg.KeyPrefix)
	var i DeviceApiKey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveDeviceAPIKeysByPrefix = `-- name: GetActiveDeviceAPIKeysByPrefix :many
SELECT id, device_id, key_hash, key_prefix, created_at, last_used_at, revoked_at
FROM device_api_keys
WHERE key_prefix = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveDeviceAPIKeysByPrefix(ctx context.Context, keyPrefix string) ([]DeviceApiKey, error) {
	rows, err := q.db.Query(ctx, getActiveDeviceAPIKeysByPrefix, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceApiKey
	for rows.Next() {
		var i DeviceApiKey
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceAPIKeyUsed = `-- name: MarkDeviceAPIKeyUsed :exec
UPDATE device_api_keys
SET last_used_at = now()
WHERE id = $1::uuid
`

func (q *Queries) MarkDeviceAPIKeyUsed(ctx context.Context, deviceApiKeyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDeviceAPIKeyUsed, deviceApiKeyID)
	return err
}

const revokeDeviceAPIKeys = `-- name: RevokeDeviceAPIKeys :many
UPDATE device_api_keys
SET revoked_at = now()
WHERE device_id = $1::uuid
  AND revoked_at IS NULL
RETURNING id, device_id, key_hash, key_prefix, created_at, last_used_at, revoked_at
`

func (q *Queries) RevokeDeviceAPIKeys(ctx context.Context, deviceID pgtype.UUID) ([]DeviceApiKey, error) {
	rows, err := q.db.Query(ctx, revokeDeviceAPIKeys, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceApiKey
	for rows.Next() {
		var i DeviceApiKey
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
