// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (
  name,
  platform,
  person_id
) VALUES (
  $1,
  $2::device_platform,
  $3::uuid
)
RETURNING id, person_id, name, platform, last_seen_at, created_at, updated_at, deactivated_at, deleted_at
`

type CreateDeviceParams struct {
	Name     string         `json:"name"`
	Platform DevicePlatform `json:"platform"`
	PersonID pgtype.UUID    `json:"person_id"`
}

// queries/devices.sql
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.Name, arg.Platform, arg.PersonID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Name,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :one
UPDATE devices
SET
  deactivated_at = now(),
  deleted_at = now(),
  updated_at = now()
WHERE id = $1::uuid
  AND deleted_at IS NULL
RETURNING id, person_id, name, platform, last_seen_at, created_at, updated_at, deactivated_at, deleted_at
`

func (q *Queries) DeleteDevice(ctx context.Context, deviceID pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, deleteDevice, deviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Name,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllDevices = `-- name: GetAllDevices :many
select id, person_id, name, platform, last_seen_at, created_at, updated_at, deactivated_at, deleted_at from devices
`

func (q *Queries) GetAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, getAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Name,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, person_id, name, platform, last_seen_at, created_at, updated_at, deactivated_at, deleted_at
FROM devices
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByID(ctx context.Context, deviceID pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, deviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Name,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDevicesByPersonID = `-- name: GetDevicesByPersonID :many
SELECT id, person_id, name, platform, last_seen_at, created_at, updated_at, deactivated_at, deleted_at
FROM devices
WHERE person_id = $1::uuid
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetDevicesByPersonID(ctx context.Context, personID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByPersonID, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.Name,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :one
UPDATE devices
SET
  last_seen_at = now(),
  updated_at = now()
WHERE id = $1::uuid
  AND deleted_at IS NULL
      RETURNING id, person_id, name, platform, last_seen_at, created_at, updated_at, deactivated_at, deleted_at
`

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, deviceID pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceLastSeen, deviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.Name,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}
