// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_pairing_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevicePairingCode = `-- name: CreateDevicePairingCode :one

INSERT INTO device_pairing_codes (
  person_id,
  code_hash,
  expires_at
) VALUES (
  $1::uuid,
  $2,
  $3
)
RETURNING id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
`

type CreateDevicePairingCodeParams struct {
	PersonID  pgtype.UUID        `json:"person_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// queries/device_pairing_codes.sql
func (q *Queries) CreateDevicePairingCode(ctx context.Context, arg CreateDevicePairingCodeParams) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, createDevicePairingCode, arg.PersonID, arg.CodeHash, arg.ExpiresAt)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CodeHash,
		&i.UsedByDevice,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePairings = `-- name: GetActivePairings :many
SELECT id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
  FROM device_pairing_codes
 where used_at is null
   and expires_at > now()
`

func (q *Queries) GetActivePairings(ctx context.Context) ([]DevicePairingCode, error) {
	rows, err := q.db.Query(ctx, getActivePairings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevicePairingCode
	for rows.Next() {
		var i DevicePairingCode
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CodeHash,
			&i.UsedByDevice,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPairings = `-- name: GetExpiredPairings :many
SELECT id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
  FROM device_pairing_codes
 where expires_at < now()
`

func (q *Queries) GetExpiredPairings(ctx context.Context) ([]DevicePairingCode, error) {
	rows, err := q.db.Query(ctx, getExpiredPairings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DevicePairingCode
	for rows.Next() {
		var i DevicePairingCode
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.CodeHash,
			&i.UsedByDevice,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairingCodeByID = `-- name: GetPairingCodeByID :one
SELECT id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
  FROM device_pairing_codes
 where id = $1::uuid
`

func (q *Queries) GetPairingCodeByID(ctx context.Context, pairingCodeID pgtype.UUID) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, getPairingCodeByID, pairingCodeID)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CodeHash,
		&i.UsedByDevice,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidDevicePairingCodeByHash = `-- name: GetValidDevicePairingCodeByHash :one
SELECT id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
FROM device_pairing_codes
WHERE code_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetValidDevicePairingCodeByHash(ctx context.Context, codeHash string) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, getValidDevicePairingCodeByHash, codeHash)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CodeHash,
		&i.UsedByDevice,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markDevicePairingCodeUsed = `-- name: MarkDevicePairingCodeUsed :one
UPDATE device_pairing_codes
SET
  used_at = now(),
  used_by_device_id = $1::uuid
WHERE id = $2::uuid
  AND used_at IS NULL
  and expired_at > now()
RETURNING id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
`

type MarkDevicePairingCodeUsedParams struct {
	DeviceID      pgtype.UUID `json:"device_id"`
	PairingCodeID pgtype.UUID `json:"pairing_code_id"`
}

func (q *Queries) MarkDevicePairingCodeUsed(ctx context.Context, arg MarkDevicePairingCodeUsedParams) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, markDevicePairingCodeUsed, arg.DeviceID, arg.PairingCodeID)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CodeHash,
		&i.UsedByDevice,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokePairingCode = `-- name: RevokePairingCode :one
UPDATE device_pairing_codes
   set expires_at = now()
 where used_at is null
   and id = $1::uuid
       RETURNING id, person_id, code_hash, used_by_device, expires_at, used_at, created_at
`

func (q *Queries) RevokePairingCode(ctx context.Context, pairingCodeID pgtype.UUID) (DevicePairingCode, error) {
	row := q.db.QueryRow(ctx, revokePairingCode, pairingCodeID)
	var i DevicePairingCode
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.CodeHash,
		&i.UsedByDevice,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
