// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one

INSERT INTO locations (
  lat,
  lng,
  accuracy,
  recorded_at,
  device_id,
  person_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::uuid,
  $6::uuid
)
RETURNING id, lat, lng, accuracy, recorded_at, received_at, device_id, person_id, created_at
`

type CreateLocationParams struct {
	Lat        float64            `json:"lat"`
	Lng        float64            `json:"lng"`
	Accuracy   float64            `json:"accuracy"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	PersonID   pgtype.UUID        `json:"person_id"`
}

// queries/locations.sql
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Lat,
		arg.Lng,
		arg.Accuracy,
		arg.RecordedAt,
		arg.DeviceID,
		arg.PersonID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Lat,
		&i.Lng,
		&i.Accuracy,
		&i.RecordedAt,
		&i.ReceivedAt,
		&i.DeviceID,
		&i.PersonID,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, lat, lng, accuracy, recorded_at, received_at, device_id, person_id, created_at
  FROM locations
 WHERE id = $1::uuid
`

func (q *Queries) GetLocationByID(ctx context.Context, locationID pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, locationID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Lat,
		&i.Lng,
		&i.Accuracy,
		&i.RecordedAt,
		&i.ReceivedAt,
		&i.DeviceID,
		&i.PersonID,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonLocations = `-- name: GetPersonLocations :many
SELECT id, lat, lng, accuracy, recorded_at, received_at, device_id, person_id, created_at
  FROM locations
 WHERE person_id = $1::uuid
`

func (q *Queries) GetPersonLocations(ctx context.Context, personID pgtype.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, getPersonLocations, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Lat,
			&i.Lng,
			&i.Accuracy,
			&i.RecordedAt,
			&i.ReceivedAt,
			&i.DeviceID,
			&i.PersonID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
