// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DevicePlatform string

const (
	DevicePlatformAndroid DevicePlatform = "android"
	DevicePlatformIos     DevicePlatform = "ios"
	DevicePlatformDesktop DevicePlatform = "desktop"
	DevicePlatformServer  DevicePlatform = "server"
	DevicePlatformOther   DevicePlatform = "other"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform `json:"device_platform"`
	Valid          bool           `json:"valid"` // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

type Device struct {
	ID            pgtype.UUID        `json:"id"`
	PersonID      pgtype.UUID        `json:"person_id"`
	Name          string             `json:"name"`
	Platform      DevicePlatform     `json:"platform"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type DeviceApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type DevicePairingCode struct {
	ID           pgtype.UUID        `json:"id"`
	PersonID     pgtype.UUID        `json:"person_id"`
	CodeHash     string             `json:"code_hash"`
	UsedByDevice pgtype.UUID        `json:"used_by_device"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Location struct {
	ID         pgtype.UUID        `json:"id"`
	Lat        float64            `json:"lat"`
	Lng        float64            `json:"lng"`
	Accuracy   float64            `json:"accuracy"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	PersonID   pgtype.UUID        `json:"person_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Person struct {
	ID            pgtype.UUID        `json:"id"`
	DisplayName   string             `json:"display_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
