// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: people.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminDeletePerson = `-- name: AdminDeletePerson :exec
DELETE FROM people WHERE id = $1::uuid
`

func (q *Queries) AdminDeletePerson(ctx context.Context, personID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeletePerson, personID)
	return err
}

const adminGetAllPeople = `-- name: AdminGetAllPeople :many
SELECT id, display_name, created_at, updated_at, deactivated_at, deleted_at
  FROM people
 ORDER BY created_at DESC
`

func (q *Queries) AdminGetAllPeople(ctx context.Context) ([]Person, error) {
	rows, err := q.db.Query(ctx, adminGetAllPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (
  display_name
) VALUES (
  $1
)
RETURNING id, display_name, created_at, updated_at, deactivated_at, deleted_at
`

// queries/people.sql
func (q *Queries) CreatePerson(ctx context.Context, displayName string) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson, displayName)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, display_name, created_at, updated_at, deactivated_at, deleted_at
  FROM people
 WHERE id = $1::uuid
   AND deleted_at IS NULL
`

func (q *Queries) GetPersonByID(ctx context.Context, personID pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, personID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setPersonToDeleted = `-- name: SetPersonToDeleted :one
UPDATE people
   SET
deleted_at = now(),
updated_at = now()
 WHERE id = $1
   AND deleted_at IS NULL
       RETURNING id, display_name, created_at, updated_at, deactivated_at, deleted_at
`

func (q *Queries) SetPersonToDeleted(ctx context.Context, personID pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, setPersonToDeleted, personID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePersonName = `-- name: UpdatePersonName :one
UPDATE people
   SET
display_name = $1,
updated_at = now()
 WHERE id = $2::uuid
   AND deleted_at IS NULL
       RETURNING id, display_name, created_at, updated_at, deactivated_at, deleted_at
`

type UpdatePersonNameParams struct {
	DisplayName string      `json:"display_name"`
	PersonID    pgtype.UUID `json:"person_id"`
}

func (q *Queries) UpdatePersonName(ctx context.Context, arg UpdatePersonNameParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePersonName, arg.DisplayName, arg.PersonID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
		&i.DeletedAt,
	)
	return i, err
}
