// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminDeletePerson(ctx context.Context, personID pgtype.UUID) error
	AdminGetAllPeople(ctx context.Context) ([]Person, error)
	// queries/devices.sql
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	// queries/device_api_keys.sql
	CreateDeviceAPIKey(ctx context.Context, arg CreateDeviceAPIKeyParams) (DeviceApiKey, error)
	// queries/device_pairing_codes.sql
	CreateDevicePairingCode(ctx context.Context, arg CreateDevicePairingCodeParams) (DevicePairingCode, error)
	// queries/locations.sql
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	// queries/people.sql
	CreatePerson(ctx context.Context, displayName string) (Person, error)
	DeleteDevice(ctx context.Context, deviceID pgtype.UUID) (Device, error)
	GetActiveDeviceAPIKeysByPrefix(ctx context.Context, keyPrefix string) (DeviceApiKey, error)
	GetActivePairings(ctx context.Context) ([]DevicePairingCode, error)
	GetAllDevices(ctx context.Context) ([]Device, error)
	GetDeviceByID(ctx context.Context, deviceID pgtype.UUID) (Device, error)
	GetDevicesByPersonID(ctx context.Context, personID pgtype.UUID) ([]Device, error)
	GetExpiredPairings(ctx context.Context) ([]DevicePairingCode, error)
	GetLocationByID(ctx context.Context, locationID pgtype.UUID) (Location, error)
	GetPairingCodeByID(ctx context.Context, pairingCodeID pgtype.UUID) (DevicePairingCode, error)
	GetPersonByID(ctx context.Context, personID pgtype.UUID) (Person, error)
	GetPersonLocations(ctx context.Context, personID pgtype.UUID) ([]Location, error)
	GetValidDevicePairingCodeByHash(ctx context.Context, codeHash string) (DevicePairingCode, error)
	MarkDeviceAPIKeyUsed(ctx context.Context, deviceApiKeyID pgtype.UUID) error
	MarkDevicePairingCodeUsed(ctx context.Context, arg MarkDevicePairingCodeUsedParams) (DevicePairingCode, error)
	RevokeDeviceAPIKeys(ctx context.Context, deviceID pgtype.UUID) ([]DeviceApiKey, error)
	RevokePairingCode(ctx context.Context, pairingCodeID pgtype.UUID) (DevicePairingCode, error)
	SetPersonToDeleted(ctx context.Context, personID pgtype.UUID) (Person, error)
	UpdateDeviceLastSeen(ctx context.Context, deviceID pgtype.UUID) (Device, error)
	UpdatePersonName(ctx context.Context, arg UpdatePersonNameParams) (Person, error)
}

var _ Querier = (*Queries)(nil)
